"""create items table

Revision ID: 6fffef4a05c1
Revises: a4f64cf19af9
Create Date: 2025-10-26 13:59:22.921825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fffef4a05c1'
down_revision: Union[str, Sequence[str], None] = 'a4f64cf19af9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('serial_number', sa.String(), nullable=True))
    op.add_column('items', sa.Column('condition', sa.String(), nullable=True))
    op.add_column('items', sa.Column('status', sa.String(), nullable=True))
    op.add_column('items', sa.Column('location', sa.String(), nullable=True))
    op.add_column('items', sa.Column('photo_url', sa.String(), nullable=True))
    op.alter_column('items', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('items', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_items_condition'), 'items', ['condition'], unique=False)
    op.create_index(op.f('ix_items_location'), 'items', ['location'], unique=False)
    op.create_index(op.f('ix_items_photo_url'), 'items', ['photo_url'], unique=False)
    op.create_index(op.f('ix_items_serial_number'), 'items', ['serial_number'], unique=False)
    op.create_index(op.f('ix_items_status'), 'items', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_status'), table_name='items')
    op.drop_index(op.f('ix_items_serial_number'), table_name='items')
    op.drop_index(op.f('ix_items_photo_url'), table_name='items')
    op.drop_index(op.f('ix_items_location'), table_name='items')
    op.drop_index(op.f('ix_items_condition'), table_name='items')
    op.alter_column('items', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('items', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('items', 'photo_url')
    op.drop_column('items', 'location')
    op.drop_column('items', 'status')
    op.drop_column('items', 'condition')
    op.drop_column('items', 'serial_number')
    # ### end Alembic commands ###
