"""initial migration

Revision ID: e07e14ed28a3
Revises: d4f7dfa5f65c
Create Date: 2025-10-23 07:52:39.760867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e07e14ed28a3'
down_revision: Union[str, Sequence[str], None] = 'd4f7dfa5f65c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 2: Fill in default value for existing rows
    op.execute("UPDATE users SET role = 'user' WHERE role IS NULL")

    # Step 3: Alter column to not nullable
    op.alter_column('users', 'role', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
